name: justsignage
adopt-info: common-info
summary: Base technologies for immersive digital signage purposes
description: |
  justSignage provides components to create beautiful, decentralized digital signage experiences 

confinement: strict
base: core20
architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: armhf
    run-on: armhf

  - build-on: arm64
    run-on: arm64

apps:
  justsignage-compositor:
    environment:
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins:${SNAP}/opt/justSignage/lib/qt5/plugins
      PATH: ${SNAP}/opt/justSignage/bin:${PATH}
    command: desktop-launch $SNAP/opt/justSignage/bin/justsignage-compositor
    plugs: [ x11, wayland, desktop, desktop-legacy, opengl, alsa, pulseaudio ]

parts:
  common-info:
    source-type: local
    source: ./
    plugin: dump
    override-pull: |
      snapcraftctl pull
      source ./common.sh
      snapcraftctl set-version "$VERSION"
      snapcraftctl set-grade "stable"
  justsignage:
    source-type: local
    source: ./
    plugin: dump
    override-build: ./build.sh -d -c
    stage-packages:
      - libaom0
      - libasn1-8-heimdal
      - libasound2
      - libass9
      - libasyncns0
      - libavc1394-0
      - libavcodec58
      - libavdevice58
      - libavfilter7
      - libavformat58
      - libavutil56
      - libbluray2
      - libboost-filesystem1.71.0
      - libboost-iostreams1.71.0
      - libboost-program-options1.71.0
      - libbrotli1
      - libbs2b0
      - libcaca0
      - libcairo-gobject2
      - libcairo2
      - libcapnp-0.7.0
      - libcdio-cdda2
      - libcdio-paranoia2
      - libcdio18
      - libchromaprint1
      - libcodec2-0.9
      - libcurl4
      - libdatrie1
      - libdbustest1
      - libdc1394-22
      - libdouble-conversion3
      - libdrm2
      - libegl1
      - libevent-2.1-7
      - libfftw3-double3
      - libflac8
      - libflite1
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgdk-pixbuf2.0-0
      - libgee-0.8-2
      - libgl1
      - libgles2
      - libglvnd0
      - libglx0
      - libgme0
      - libgomp1
      - libgraphite2-3
      - libgsettings-qt1
      - libgsm1
      - libgssapi3-heimdal
      - libharfbuzz0b
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libicu66
      - libiec61883-0
      - libjack-jackd2-0
      - libjpeg-turbo8
      - libjson-glib-1.0-0
      - libkrb5-26-heimdal
      - liblcms2-2
      - libldap-2.4-2
      - liblilv-0-0
      - liblttng-ust0
      - libminizip1
      - libmiral3
      - libmirclient9
      - libmircommon7
      - libmircookie2
      - libmircore1
      - libmirplatform17
      - libmirprotobuf3
      - libmirserver53
      - libmirwayland0
      - libmp3lame0
      - libmpg123-0
      - libmysofa1
      - libnghttp2-14
      - libnorm1
      - libnspr4
      - libnss3
      - libnuma1
      - libogg0
      - libopenal1
      - libopenjp2-7
      - libopenmpt0
      - libopus0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpcre2-16-0
      - libpgm-5.2-0
      - libpixman-1-0
      - libpng16-16
      - libpostproc55
      - libprocess-cpp3
      - libprotobuf-lite17
      - libpsl5
      - libpulse0
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5network5
      - libqt5opengl5
      - libqt5positioning5
      - libqt5qml5
      - libqt5quick5
      - libqt5sensors5
      - libqt5sql5
      - libqt5test5
      - libqt5webchannel5
      - libqt5webengine5
      - libqt5webenginecore5
      - libqt5widgets5
      - libqtdbusmock1
      - libqtdbustest1
      - libraw1394-11
      - libre2-5
      - libroken18-heimdal
      - librsvg2-2
      - librtmp1
      - librubberband2
      - libsamplerate0
      - libsasl2-2
      - libsdl2-2.0-0
      - libserd-0-0
      - libshine3
      - libslang2
      - libsnappy1v5
      - libsndfile1
      - libsndio7.0
      - libsodium23
      - libsord-0-0
      - libsoxr0
      - libspeex1
      - libsratom-0-0
      - libssh-4
      - libssh-gcrypt-4
      - libswresample3
      - libswscale5
      - libthai0
      - libtheora0
      - libtwolame0
      - liburcu6
      - libusb-1.0-0
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libvidstab1.1
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libvpx6
      - libwavpack1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-server0
      - libwebp6
      - libwebpdemux2
      - libwebpmux3
      - libwind0-heimdal
      - libx11-6
      - libx264-155
      - libx265-179
      - libxau6
      - libxcb-composite0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb1
      - libxcursor1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml2
      - libxrandr2
      - libxrender1
      - libxslt1.1
      - libxss1
      - libxv1
      - libxvidcore4
      - libxxf86vm1
      - libyaml-cpp0.6
      - libzeitgeist-2.0-0
      - libzmq5
      - libzvbi0
      - ocl-icd-libopencl1
    organize:
      opt: opt/
    after: [ desktop-qt5 ]
  desktop-qt5:
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
      - xdg-user-dirs
